steps:
- name: maven:3.6.0-jdk-11-slim
  entrypoint: 'mvn'
  args: ['clean', 'install', 'package', '-DskipTests']
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/xanadusamplewebapp:latest", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/xanadusamplewebapp:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s/
  - --image=gcr.io/$PROJECT_ID/xanadusamplewebapp:latest
  - --location=asia-east1-a
  - --cluster=anthos-sample-cluster1