apiVersion: apps/v1
kind: Deployment
metadata:
    name: xanaduwebapp-deployment
    labels:
        app: xanaduwebapp
spec:
    replicas: 1
    selector:
        matchLabels:
            app: xanaduwebapp
    template: 
        metadata:
            labels:
                app: xanaduwebapp
        spec:
            containers:
            - name: k8s-demo
              image: gcr.io/tde-coe-anthos/xanadusamplewebapp:latest
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: xanaduwebapp
    labels:
        app: xanaduwebapp
spec:
    ports:
        - name: http-port
          port: 80
          targetPort: 8080
    selector: 
        app: xanaduwebapp
    type: LoadBalancer
